Add coinbase adapter
Web3Auth/Web3Auth pull request #104
Opened 2022-03-29 10:27 UTC by chaitanyapotti

2022-03-29 10:46 UTC, himanshuchawla009 requested changes

2022-03-29 10:46 UTC, himanshuchawla009 commented on packages/adapters/coinbase-adapter/README.md
> +# `@web3auth/torus-wallet-adapter`
update readme name

2022-03-29 10:46 UTC, himanshuchawla009 commented on packages/adapters/coinbase-adapter/package.json
> +  "homepage": "https://github.com/Web3Auth/Web3Auth/tree/main/packages/core#readme",
correct home page url

2022-03-29 10:46 UTC, himanshuchawla009 commented on packages/adapters/coinbase-adapter/src/coinbaseAdapter.ts
> +    if (!this.coinbaseProvider) throw WalletLoginError.notConnectedError("Not able to connect with coinbase");
better to change the error message, "Adapter is not initialized"

2022-03-29 12:10 UTC, himanshuchawla009 commented on packages/adapters/coinbase-adapter/src/coinbaseAdapter.ts
> +    this.provider?.removeAllListeners();
coinbaseInstance.disconnect() function should be called here.

2022-03-29 16:18 UTC, himanshuchawla009 approved these changes
lgtm

2022-03-29 17:06 UTC, tainguyentt commented on examples/vue-app/src/home.vue
> +  }
uncheck Coinbase in from this list won't work. It still shows the Coinbase wallet because when we configureAdapter(CoinbaseAdapter), it's added to the wallet adapters and modalConfig won't take effect

2022-03-29 17:06 UTC, tainguyentt approved these changes
lgtm

2022-03-30 04:44 UTC, chaitanyapotti commented on examples/vue-app/src/home.vue
> +  }
Let's add this as an issue because it should take effect.

2022-03-30 04:44 UTC, merged