Update README.md
Web3Auth/Web3Auth pull request #146
Opened 2022-04-19 10:40 UTC by yashovardhan

Added a new base documentation for Web3Auth. Please let me know if we need anything else in this base readme. I will add more READMEs later for each of our packages as well.

2022-04-19 13:03 UTC, himanshuchawla009 commented on README.md
> +- [`@web3auth/wallet-connect-v1-adapter`](https://npmjs.com/package/@web3auth/wallet-connect-v1-adapter)
add coinbase adapter as well.

2022-04-19 13:04 UTC, himanshuchawla009 requested changes

2022-04-19 13:04 UTC, himanshuchawla009 commented on README.md
> +- [`@web3auth/wallet-connect-v1-adapter`](https://npmjs.com/package/@web3auth/wallet-connect-v1-adapter)
add coinbase adapter as well. Also add some info about plugins may be now or later in readme.

2022-04-22 18:21 UTC, himanshuchawla009 commented on README.md
> +- [`@web3auth/wallet-connect-v1-adapter`](https://npmjs.com/package/@web3auth/wallet-connect-v1-adapter)
merging it for now. But plz make these updates in future pr. @yashovardhan

2022-04-22 18:21 UTC, himanshuchawla009 approved these changes
lgtm

2022-04-27 09:28 UTC, chaitanyapotti approved these changes
lgtm

2022-04-27 09:28 UTC, merged