feat: cognito working example
Web3Auth/Web3Auth pull request #184
Opened 2022-05-15 20:52 UTC by rinzler99

2022-05-17 09:29 UTC, himanshuchawla009 requested changes

2022-05-17 09:29 UTC, himanshuchawla009 commented on examples/cognito-react-example/config-overrides copy.js
> +const webpack = require("webpack");
remove this file

2022-05-17 09:29 UTC, himanshuchawla009 commented on examples/cognito-react-example/README.md
> +- Now go to your hosted app domain , it should show you hosted ui with google login button.
implementation is different from readme, we are not using cognito hosted UI right, we are using custom ui.  Please update the steps in readme accordingly.

2022-05-17 09:29 UTC, himanshuchawla009 commented on examples/cognito-react-example/src/services/web3auth.tsx
> +              clientId: "29343gi24opt30vsa5s7u8gfvg",
add code comment here about client id.

2022-05-17 09:29 UTC, himanshuchawla009 commented on examples/cognito-react-example/src/services/web3auth.tsx
> +          response_type: "token",
add code comment about each variable here.

2022-05-17 09:30 UTC, himanshuchawla009 commented
there is some flicker while login, don't show logged in view on clicking of login button as shown in video:-

https://user-images.githubusercontent.com/14052374/168779037-2ac9b071-d807-4ae3-9f3b-fa2107589789.mov

2022-05-17 16:23 UTC, rinzler99 commented on examples/cognito-react-example/README.md
> +- Now go to your hosted app domain , it should show you hosted ui with google login button.
we are using hosted UI for aws cognito not for web3auth, i think this is right.

2022-05-17 16:26 UTC, himanshuchawla009 commented on examples/cognito-react-example/README.md
> +- Now go to your hosted app domain , it should show you hosted ui with google login button.
can you add the screenshot of hosted ui.

2022-05-18 07:12 UTC, himanshuchawla009 approved these changes
lgtm

2022-05-18 07:14 UTC, chaitanyapotti approved these changes
lgtm

2022-05-18 07:14 UTC, merged