feat: self custodial design for w3a model
Web3Auth/Web3Auth pull request #199
Opened 2022-05-23 13:25 UTC by rinzler99

2022-05-23 15:49 UTC, chaitanyapotti commented on packages/ui/src/components/Modal.tsx
> +    cls="w3a-button--icon-overlap"
this will crash the app if there's only one login icon

2022-05-23 15:50 UTC, chaitanyapotti commented on packages/ui/src/components/Modal.tsx
> +    imageId={`login-${loginIcons[0]}${isDark && hasLightIcons.includes(loginIcons[0]) ? "-light" : ""}`}
Fix your linter.!!

2022-05-23 15:51 UTC, chaitanyapotti commented on packages/ui/src/components/Modal.tsx
> +            {loginIcons.length == 3?
Write better logic.
use a loop

2022-05-23 15:51 UTC, chaitanyapotti commented on packages/ui/src/components/Modal.tsx
> +                  {(areSocialLoginsVisible || isEmailPassworedlessLoginVisible) && socialLoginButton}
No spelling mistakes pls

2022-05-23 15:52 UTC, chaitanyapotti commented on packages/ui/src/components/SocialLogins.tsx
> +  const adapterExpandText = isExpanded ? "" : "";
both cases can't be the same

2022-05-23 15:52 UTC, chaitanyapotti commented
Add screenshots of your final design.

2022-05-24 02:53 UTC, rinzler99 commented on packages/ui/src/components/Modal.tsx
> +                  {(areSocialLoginsVisible || isEmailPassworedlessLoginVisible) && socialLoginButton}
that was already written logic by someone, will change that spelling btw.

2022-05-24 02:54 UTC, rinzler99 commented on packages/ui/src/components/SocialLogins.tsx
> +  const adapterExpandText = isExpanded ? "" : "";
the case is for sohwing the string msg which is "view less options" or "view more options", but in new modal these string msges are removed.

2022-05-24 03:33 UTC, rinzler99 commented on packages/ui/src/components/Modal.tsx
> +    imageId={`login-${loginIcons[0]}${isDark && hasLightIcons.includes(loginIcons[0]) ? "-light" : ""}`}
ok

2022-05-24 03:33 UTC, rinzler99 commented on packages/ui/src/components/Modal.tsx
> +            {loginIcons.length == 3?
ok

2022-05-24 04:38 UTC, rinzler99 commented on packages/ui/src/components/SocialLogins.tsx
> +  const adapterExpandText = isExpanded ? "" : "";
i Have removed the code to show any msg.

2022-05-24 04:39 UTC, rinzler99 commented
> Add screenshots of your final design.

https://www.loom.com/share/728a21c0afb24e7d97606587ad1272e6 pls find the loom recording attached.

2022-05-24 09:39 UTC, himanshuchawla009 requested changes

2022-05-24 09:39 UTC, himanshuchawla009 commented on packages/ui/src/components/Modal.tsx
> +      if (tempExternalWalletList.includes("metamask")) {
use constants for wallet names, all constants are defined in base package.

2022-05-24 09:39 UTC, himanshuchawla009 commented on packages/ui/src/components/Modal.tsx
> +        if (loginsList[i] !== "facebook") tempIconList.push(loginsList[i]);
plz leave comments about these edge cases, why you are looping through everything except facebook?

2022-05-24 09:39 UTC, himanshuchawla009 commented on packages/ui/src/interfaces.ts
> +  externalWalletList: string[];
you already have externalWalletsConfig here, no need to create a new variable "externalWalletList"

2022-05-24 09:39 UTC, himanshuchawla009 commented on packages/ui/src/components/Modal.tsx
> +                  {modalState.hiddenSocialLogin ? (
plz chunk out this conditional logic into different components. You can create new components to contain social logins container and wallets container and use conditionals inside those components.

2022-05-24 09:48 UTC, rinzler99 commented on packages/ui/src/components/Modal.tsx
> +        setWalletIcon(tempExternalWalletList[0]);
the priority is we first check if metamask is present if it is not then we check if wallect connect is present if it is also not present then we choose anything to as icon whichi s selelcted that is why we are selecting 0th element from list of wallets.

2022-05-24 09:50 UTC, rinzler99 commented on packages/ui/src/interfaces.ts
> +  externalWalletList: string[];
externalwalletconfig will load after we click on the "external wallet" button but we want to show icons of selected wallets before we press on the button

2022-05-24 09:51 UTC, rinzler99 commented on packages/ui/src/components/Modal.tsx
> +                  {modalState.hiddenSocialLogin ? (
ok

2022-05-24 09:54 UTC, rinzler99 commented on packages/ui/src/components/Modal.tsx
> +      if (tempExternalWalletList.includes("metamask")) {
ok

2022-05-24 10:40 UTC, himanshuchawla009 requested changes

2022-05-24 10:40 UTC, himanshuchawla009 commented on packages/ui/src/components/Modal.tsx
> +                  {modalState.hiddenSocialLogin ? (
but can u move following code in one component, so that main logic gets more readable ``` <button
                          type="button"
                          className="w3a-external-back w3ajs-external-back"
                          onClick={() => {
                            setModalState((prevState) => {
                              return { ...prevState, hiddenSocialLogin: !modalState.hiddenSocialLogin };
                            });
                          }}
                        >
                          <Icon iconName="arrow-left-new" cls="back-button-arrow" />
                          <div className="w3a-footer__secured">Back</div>
                        </button>
                      )}
                      {areSocialLoginsVisible ? (
                        <SocialLogins
                          handleSocialLoginClick={(params: SocialLoginEventType) => preHandleSocialWalletClick(params)}
                          socialLoginsConfig={modalState.socialLoginsConfig}
                        />```

2022-05-24 10:40 UTC, himanshuchawla009 commented on packages/ui/src/components/Modal.tsx
> +        if (loginsList[i] !== "facebook") tempIconList.push(loginsList[i]);
i believe you can do this logic in above Object.keys(modalState.socialLoginsConfig.loginMethods).filter directly instead of using another loop.

2022-05-24 10:49 UTC, rinzler99 commented on packages/ui/src/components/Modal.tsx
> +        if (loginsList[i] !== "facebook") tempIconList.push(loginsList[i]);
we want only three icons filter will give us more than that

2022-05-25 04:22 UTC, himanshuchawla009 commented on packages/ui/src/components/Modal.tsx
> +        if (loginsList[i] !== "facebook") tempIconList.push(loginsList[i]);
or you can use reduce function

2022-07-28 09:11 UTC, chaitanyapotti commented
Not doing this anymore

2022-07-28 09:11 UTC, closed without merging