added rwa application support in auth0
Web3Auth/Web3Auth pull request #208
Opened 2022-06-01 07:50 UTC by rinzler99

2022-06-01 09:41 UTC, himanshuchawla009 requested changes

2022-06-01 09:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/app/.env.development
> +REACT_APP_VERIFIER="web3auth-firebase-demo"
change the name to : web3auth-auth0-demo

2022-06-01 09:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/app/README.md
> +1. Your domain name in loginRWA method
load it from env variables.

2022-06-01 09:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/api/server.js
> +app.get('/callback', (req, res) => {
add eslint for your node js code.

2022-06-01 09:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/api/views/partials/header.ejs
> +<!DOCTYPE html>
are we using ejs files, if not remove them

2022-06-01 09:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/app/src/components/Main.tsx
>    }
remove this empty finally block.

2022-06-01 09:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/app/src/components/Main.tsx
> +      window.location.href="https://torus-test.auth0.com/authorize?scope=openid&response_type=code&client_id=FX0BwYwDtD6p0yTOjjIykjLbtxXszfkR&redirect_uri=http://localhost:3001/callback&state=STATE&c
load this domain from env variables. and also load redirect_uri.

2022-06-01 09:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/app/src/services/web3authRWA.tsx
>    chain: string;
this file is not being used, remove it

2022-06-01 09:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/app/src/components/MainRWA.tsx
> +  const token = jwt == null ? "" : jwt.toString();
toString() is not required

2022-06-01 11:50 UTC, rinzler99 commented on examples/auth0-react-example/app/.env.development
> +REACT_APP_VERIFIER="web3auth-firebase-demo"
changed

2022-06-01 11:51 UTC, rinzler99 commented on examples/auth0-react-example/api/server.js
> +app.get('/callback', (req, res) => {
added eslint for nodejs code.

2022-06-01 11:51 UTC, rinzler99 commented on examples/auth0-react-example/api/views/partials/header.ejs
> +<!DOCTYPE html>
they were removed locally , done same on remote repo

2022-06-01 11:52 UTC, rinzler99 commented on examples/auth0-react-example/app/src/components/Main.tsx
>    }
removed

2022-06-01 11:52 UTC, rinzler99 commented on examples/auth0-react-example/app/src/components/Main.tsx
> +      window.location.href="https://torus-test.auth0.com/authorize?scope=openid&response_type=code&client_id=FX0BwYwDtD6p0yTOjjIykjLbtxXszfkR&redirect_uri=http://localhost:3001/callback&state=STATE&c
done

2022-06-01 11:52 UTC, rinzler99 commented on examples/auth0-react-example/app/src/components/MainRWA.tsx
> +  const token = jwt == null ? "" : jwt.toString();
done

2022-06-03 07:41 UTC, himanshuchawla009 requested changes

2022-06-03 07:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/api/.env.example
> +CLIENT_SECRET =  TgwKmD3Jd9iXQu_Fhj0w1smrm32NSgHQ3gzKBY_K6YTU3klQemME7UGxpbr3DlC3
remove secret !

2022-06-03 07:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/app/src/components/Main.tsx
> +                "https://torus-test.auth0.com/authorize?scope=openid&response_type=code&client_id=FX0BwYwDtD6p0yTOjjIykjLbtxXszfkR&redirect_uri=https://auth0-web3auth-example.herokuapp.com/callback&s
|| condition is unnecessary. Also, write clean code plz.

2022-06-03 07:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/app/src/services/web3auth.tsx
> +          domain: "https://torus-test.auth0.com",
keep all auth0 and verifier conf in env variables as well. Some conf you are loading from env but  some is still static.

2022-06-03 07:41 UTC, himanshuchawla009 commented on examples/auth0-react-example/app/src/services/web3auth.tsx
> +    window.sessionStorage.clear();
clear storage before redirecting.

2022-06-03 10:41 UTC, rinzler99 commented on examples/auth0-react-example/app/src/services/web3auth.tsx
> +    window.sessionStorage.clear();
done

2022-06-03 10:42 UTC, rinzler99 commented on examples/auth0-react-example/app/src/services/web3auth.tsx
> +          domain: "https://torus-test.auth0.com",
done

2022-06-03 10:42 UTC, rinzler99 commented on examples/auth0-react-example/app/src/components/Main.tsx
> +                "https://torus-test.auth0.com/authorize?scope=openid&response_type=code&client_id=FX0BwYwDtD6p0yTOjjIykjLbtxXszfkR&redirect_uri=https://auth0-web3auth-example.herokuapp.com/callback&s
done

2022-06-03 10:42 UTC, rinzler99 commented on examples/auth0-react-example/api/.env.example
> +CLIENT_SECRET =  TgwKmD3Jd9iXQu_Fhj0w1smrm32NSgHQ3gzKBY_K6YTU3klQemME7UGxpbr3DlC3
done

2022-06-18 08:52 UTC, himanshuchawla009 approved these changes
lgtm

2022-07-14 12:02 UTC, chaitanyapotti approved these changes
lgtm

2022-07-14 12:03 UTC, merged