Feat/torus wallet plugin
Web3Auth/Web3Auth pull request #78
Opened 2022-03-07 05:59 UTC by himanshuchawla009

2022-03-14 12:06 UTC, chaitanyapotti commented on packages/plugins/torus-wallet-connector-plugin/src/plugin.ts
> +        showTorusButton: false,
people want to see the button. Pls don't change this default.
Also, object || undefined will always be object

2022-03-14 12:07 UTC, chaitanyapotti commented on packages/plugins/torus-wallet-connector-plugin/src/plugin.ts
> +      log.warn("unsupported method", error, TorusWalletPluginError.unsupportedAdapter());
pls check the error code before throwing

2022-03-14 12:10 UTC, chaitanyapotti commented on packages/plugins/torus-wallet-connector-plugin/src/plugin.ts
> +      await this.torusWalletInstance?.setProvider({
throw explicity if torusWalletinstance is not available

2022-03-14 12:10 UTC, chaitanyapotti requested changes
pls make the necessary changes

2022-03-14 14:30 UTC, himanshuchawla009 commented on packages/plugins/torus-wallet-connector-plugin/src/plugin.ts
> +        showTorusButton: false,
if we will show this button before login then user might click on the button and it will open login modal for wallet instead of web3auth.

2022-03-14 19:20 UTC, himanshuchawla009 commented on packages/core/src/core.ts
> +            if (error.message.includes("unsupported adapter")) {
handled with error code now

2022-03-14 19:20 UTC, himanshuchawla009 commented on packages/plugins/base-plugin/src/IPlugin.ts
> +  initWithWeb3Auth(web3auth: T): Promise<void>;
fixed, added a IWeb3auth interface in base

2022-03-14 19:20 UTC, himanshuchawla009 commented on packages/plugins/torus-wallet-connector-plugin/src/plugin.ts
> +      log.warn("unsupported method", error, TorusWalletPluginError.unsupportedAdapter());
fixed

2022-03-14 19:21 UTC, himanshuchawla009 commented on packages/plugins/torus-wallet-connector-plugin/src/plugin.ts
> +      await this.torusWalletInstance?.setProvider({
fixed

2022-03-15 19:27 UTC, chaitanyapotti approved these changes
lgtm

2022-03-15 19:27 UTC, merged